# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2025-2026 Caleb Kemere, Rice University
#
# GENERATED by scripts/build_fabric.py -- DO NOT EDIT. Change the builder and
# rerun `scripts/build_fabric.py acq_imu_port_b` to regenerate.
#
# Variant acq_imu_port_b: port A = lvds, port B = imu.

# Pin constraints: the LVDS SPI lanes per cable, plus I2C on the freed
# second-CIPO balls for any 'imu' port. Added explicitly by
# scripts/build_fabric.tcl -- it must NOT live in the globbed constraints/
# dir, or the plain acquisition build would double-assign these ports.
# The second-CIPO balls are LVCMOS25 I2C on an imu port and LVDS_25 (CIPO1)
# on an lvds/128-ch port -- same physical balls, reconfigured per bitstream.

set CLK [get_clocks clk_out1_design_1_clk_wiz_0_84M_175M_0]

#==============================================================================
# PORT A (spi_lvds_0) -- 128-ch, full CIPO0 + CIPO1 LVDS
#==============================================================================
# SCLK / CSN / COPI (broadcast outputs)
set_property IOSTANDARD LVDS_25 [get_ports {spi_lvds_0_sclk_p spi_lvds_0_sclk_n}]
set_property PACKAGE_PIN E17 [get_ports spi_lvds_0_sclk_p]
set_property PACKAGE_PIN D18 [get_ports spi_lvds_0_sclk_n]
set_output_delay -clock $CLK -max  2.0 [get_ports {spi_lvds_0_sclk_p spi_lvds_0_sclk_n}]
set_output_delay -clock $CLK -min -2.0 [get_ports {spi_lvds_0_sclk_p spi_lvds_0_sclk_n}]
set_property IOSTANDARD LVDS_25 [get_ports {spi_lvds_0_csn_p spi_lvds_0_csn_n}]
set_property PACKAGE_PIN D19 [get_ports spi_lvds_0_csn_p]
set_property PACKAGE_PIN D20 [get_ports spi_lvds_0_csn_n]
set_output_delay -clock $CLK -max  2.0 [get_ports {spi_lvds_0_csn_p spi_lvds_0_csn_n}]
set_output_delay -clock $CLK -min -2.0 [get_ports {spi_lvds_0_csn_p spi_lvds_0_csn_n}]
set_property IOSTANDARD LVDS_25 [get_ports {spi_lvds_0_copi_p spi_lvds_0_copi_n}]
set_property PACKAGE_PIN F16 [get_ports spi_lvds_0_copi_p]
set_property PACKAGE_PIN F17 [get_ports spi_lvds_0_copi_n]
set_output_delay -clock $CLK -max  2.0 [get_ports {spi_lvds_0_copi_p spi_lvds_0_copi_n}]
set_output_delay -clock $CLK -min -2.0 [get_ports {spi_lvds_0_copi_p spi_lvds_0_copi_n}]
# CIPO0 (input)
set_property IOSTANDARD LVDS_25 [get_ports {spi_lvds_0_cipo0_p spi_lvds_0_cipo0_n}]
set_property PACKAGE_PIN E18 [get_ports spi_lvds_0_cipo0_p]
set_property PACKAGE_PIN E19 [get_ports spi_lvds_0_cipo0_n]
set_property DIFF_TERM TRUE  [get_ports spi_lvds_0_cipo0_p]
set_input_delay -clock $CLK -max 3.0 [get_ports {spi_lvds_0_cipo0_p spi_lvds_0_cipo0_n}]
set_input_delay -clock $CLK -min 0.5 [get_ports {spi_lvds_0_cipo0_p spi_lvds_0_cipo0_n}]
# CIPO1 (input)
set_property IOSTANDARD LVDS_25 [get_ports {spi_lvds_0_cipo1_p spi_lvds_0_cipo1_n}]
set_property PACKAGE_PIN M19 [get_ports spi_lvds_0_cipo1_p]
set_property PACKAGE_PIN M20 [get_ports spi_lvds_0_cipo1_n]
set_property DIFF_TERM TRUE  [get_ports spi_lvds_0_cipo1_p]
set_input_delay -clock $CLK -max 3.0 [get_ports {spi_lvds_0_cipo1_p spi_lvds_0_cipo1_n}]
set_input_delay -clock $CLK -min 0.5 [get_ports {spi_lvds_0_cipo1_p spi_lvds_0_cipo1_n}]
# Slew / drive on this port's outputs
set_property SLEW FAST [get_ports {spi_lvds_0_sclk_p spi_lvds_0_csn_p spi_lvds_0_copi_p}]
set_property DRIVE 12  [get_ports {spi_lvds_0_sclk_p spi_lvds_0_csn_p spi_lvds_0_copi_p}]

#==============================================================================
# PORT B (spi_lvds_1) -- 64-ch, CIPO0 only + I2C on the freed CIPO1 balls
#==============================================================================
# SCLK / CSN / COPI (broadcast outputs)
set_property IOSTANDARD LVDS_25 [get_ports {spi_lvds_1_sclk_p spi_lvds_1_sclk_n}]
set_property PACKAGE_PIN J20 [get_ports spi_lvds_1_sclk_p]
set_property PACKAGE_PIN H20 [get_ports spi_lvds_1_sclk_n]
set_output_delay -clock $CLK -max  2.0 [get_ports {spi_lvds_1_sclk_p spi_lvds_1_sclk_n}]
set_output_delay -clock $CLK -min -2.0 [get_ports {spi_lvds_1_sclk_p spi_lvds_1_sclk_n}]
set_property IOSTANDARD LVDS_25 [get_ports {spi_lvds_1_csn_p spi_lvds_1_csn_n}]
set_property PACKAGE_PIN F19 [get_ports spi_lvds_1_csn_p]
set_property PACKAGE_PIN F20 [get_ports spi_lvds_1_csn_n]
set_output_delay -clock $CLK -max  2.0 [get_ports {spi_lvds_1_csn_p spi_lvds_1_csn_n}]
set_output_delay -clock $CLK -min -2.0 [get_ports {spi_lvds_1_csn_p spi_lvds_1_csn_n}]
set_property IOSTANDARD LVDS_25 [get_ports {spi_lvds_1_copi_p spi_lvds_1_copi_n}]
set_property PACKAGE_PIN H15 [get_ports spi_lvds_1_copi_p]
set_property PACKAGE_PIN G15 [get_ports spi_lvds_1_copi_n]
set_output_delay -clock $CLK -max  2.0 [get_ports {spi_lvds_1_copi_p spi_lvds_1_copi_n}]
set_output_delay -clock $CLK -min -2.0 [get_ports {spi_lvds_1_copi_p spi_lvds_1_copi_n}]
# CIPO0 (input)
set_property IOSTANDARD LVDS_25 [get_ports {spi_lvds_1_cipo0_p spi_lvds_1_cipo0_n}]
set_property PACKAGE_PIN L14 [get_ports spi_lvds_1_cipo0_p]
set_property PACKAGE_PIN L15 [get_ports spi_lvds_1_cipo0_n]
set_property DIFF_TERM TRUE  [get_ports spi_lvds_1_cipo0_p]
set_input_delay -clock $CLK -max 3.0 [get_ports {spi_lvds_1_cipo0_p spi_lvds_1_cipo0_n}]
set_input_delay -clock $CLK -min 0.5 [get_ports {spi_lvds_1_cipo0_p spi_lvds_1_cipo0_n}]
# Slew / drive on this port's outputs
set_property SLEW FAST [get_ports {spi_lvds_1_sclk_p spi_lvds_1_csn_p spi_lvds_1_copi_p}]
set_property DRIVE 12  [get_ports {spi_lvds_1_sclk_p spi_lvds_1_csn_p spi_lvds_1_copi_p}]

# I2C on the freed CIPO1 balls (scl K16, sda J16); open-drain LVCMOS25.
set_property PACKAGE_PIN K16 [get_ports iic_b_scl_io]
set_property PACKAGE_PIN J16 [get_ports iic_b_sda_io]
set_property IOSTANDARD LVCMOS25 [get_ports {iic_b_scl_io iic_b_sda_io}]
set_property SLEW SLOW           [get_ports {iic_b_scl_io iic_b_sda_io}]
set_property DRIVE 8             [get_ports {iic_b_scl_io iic_b_sda_io}]

