# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2025-2026 Caleb Kemere, Rice University
#
# GENERATED by scripts/build_fabric.py -- DO NOT EDIT. Change the builder and
# rerun `scripts/build_fabric.py acq_imu_port_a` to regenerate.
#
# Variant acq_imu_port_a: port A = imu, port B = lvds.

# BD overlay: sourced AFTER design_1_bd.tcl, it transforms the stock
# acquisition design_1 in place. For each 'imu' cable it swaps the LVDS
# buffer for the CIPO0-only fork (freeing the CIPO1 balls) and grafts an
# AXI IIC onto GP0; 'lvds' cables are left as the stock 128-ch buffer.

current_bd_design design_1

# --- Port A: CIPO0-only buffer, LVDS side re-exposed as plain ports ---
delete_bd_objs [get_bd_cells intan_spi_lvds_buffer_0] [get_bd_intf_ports spi_lvds_0]
create_bd_cell -type module -reference intan_spi_lvds_buffer_cipo0 intan_spi_lvds_buffer_0
connect_bd_intf_net [get_bd_intf_pins data_generator/intan_spi] [get_bd_intf_pins intan_spi_lvds_buffer_0/intan_spi]
foreach {suf dir} {sclk_p O sclk_n O csn_p O csn_n O copi_p O copi_n O cipo0_p I cipo0_n I} {
    create_bd_port -dir $dir spi_lvds_0_$suf
    connect_bd_net [get_bd_ports spi_lvds_0_$suf] [get_bd_pins intan_spi_lvds_buffer_0/spi_$suf]
}

# Grow the GP0 smartconnect (stock 3 masters) for the 1 IIC(s).
set_property -dict [list CONFIG.NUM_MI {4}] [get_bd_cells smartconnect_0]

# --- Port A: axi_iic_a at 0x43D00000 on smartconnect M03 ---
create_bd_cell -type ip -vlnv xilinx.com:ip:axi_iic:2.1 axi_iic_a
set_property -dict [list CONFIG.C_SCL_INERTIAL_DELAY {5} CONFIG.IIC_FREQ_KHZ {100}] [get_bd_cells axi_iic_a]
connect_bd_intf_net [get_bd_intf_pins smartconnect_0/M03_AXI] [get_bd_intf_pins axi_iic_a/S_AXI]
make_bd_intf_pins_external [get_bd_intf_pins axi_iic_a/IIC]
set_property name iic_a [get_bd_intf_ports IIC_0]
connect_bd_net -net clk_wiz_0_84M_clk_out2 [get_bd_pins axi_iic_a/s_axi_aclk]
connect_bd_net -net proc_sys_reset_175MHz_interconnect_aresetn [get_bd_pins axi_iic_a/s_axi_aresetn]
assign_bd_address -offset 0x43D00000 -range 0x00010000 -target_address_space [get_bd_addr_spaces processing_system7_0/Data] [get_bd_addr_segs axi_iic_a/S_AXI/Reg] -force

validate_bd_design
save_bd_design
