# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2025-2026 Caleb Kemere, Rice University
#
# Parameterized builder for the acq_imu_* acquisition fabric variants.
#
# Each cable is one of two modes:
#   * 'lvds' -- 128-ch: full CIPO0 + CIPO1 LVDS, the stock acquisition buffer.
#   * 'imu'  -- 64-ch: CIPO0-only LVDS (the intan_spi_lvds_buffer_cipo0 fork drops
#              the CIPO1 differential pair), and the freed second-CIPO balls carry
#              a single-ended I2C bus (an AXI IIC) for a per-cable BNO055.
#
# The 2x2 of (port A) x (port B) gives the fabric family. This script emits, for a
# chosen variant, the BD overlay Tcl (transforms the stock design_1 in place) and
# the pin XDC, then runs Vivado (scripts/build_fabric.tcl) to produce the .xsa.
#
# It is the single source of truth: the generated overlay/XDC carry a DO-NOT-EDIT
# header and are regenerated on every build. design_1_bd.tcl and the RTL stay the
# shared base; this only expresses the per-variant diff. See docs/boot.md
# and the memory note fabric-variant-builds.
#
#   scripts/build_fabric.py <variant>            # generate + synthesize -> .xsa
#   scripts/build_fabric.py <variant> --emit-only  # write overlay+XDC, no Vivado
#
# Variants: acq_imu_both, acq_imu_port_a, acq_imu_port_b.

import os
import sys
import subprocess

PART = "xc7z020clg400-1"
CLK = "clk_out1_design_1_clk_wiz_0_84M_175M_0"  # the 84/175 MHz source, per intan_io.xdc

# Per-port pin data (xc7z020clg400 balls), lifted from intan_io.xdc (LVDS lanes)
# and acq_imu_both_pins.xdc (I2C). In 'imu' mode the CIPO1 pair
# is freed for I2C: scl = cipo1_p ball, sda = cipo1_n ball.
#   idx           -- the buffer cell / interface-port / flattened-port index.
#   dg            -- the data_generator single-ended interface pin for this cable.
#   iic / base    -- AXI IIC instance name + its GP0 address (only used in imu mode).
PORTS = {
    "a": {
        "idx": "0", "dg": "intan_spi",   "iic": "axi_iic_a", "iic_pfx": "iic_a", "base": "0x43D00000",
        "sclk": ("E17", "D18"), "csn": ("D19", "D20"), "copi": ("F16", "F17"),
        "cipo0": ("E18", "E19"), "cipo1": ("M19", "M20"),
    },
    "b": {
        "idx": "1", "dg": "intan_spi_b", "iic": "axi_iic_b", "iic_pfx": "iic_b", "base": "0x43D10000",
        "sclk": ("J20", "H20"), "csn": ("F19", "F20"), "copi": ("H15", "G15"),
        "cipo0": ("L14", "L15"), "cipo1": ("K16", "J16"),
    },
}
PORT_ORDER = ["a", "b"]

# variant -> {port: mode}. acq (lvds+lvds) is the stock build.sh fabric, no overlay.
VARIANTS = {
    "acq_imu_both":   {"a": "imu",  "b": "imu"},
    "acq_imu_port_a": {"a": "imu",  "b": "lvds"},
    "acq_imu_port_b": {"a": "lvds", "b": "imu"},
}

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OVERLAY_DIR = os.path.join(ROOT, "programmable_logic", "block_design")
XDC_DIR = os.path.join(ROOT, "programmable_logic", "constraints", "variants")

GEN_HEADER = (
    "# SPDX-License-Identifier: MIT\n"
    "# SPDX-FileCopyrightText: 2025-2026 Caleb Kemere, Rice University\n"
    "#\n"
    "# GENERATED by scripts/build_fabric.py -- DO NOT EDIT. Change the builder and\n"
    "# rerun `scripts/build_fabric.py {variant}` to regenerate.\n"
    "#\n"
    "# Variant {variant}: port A = {a}, port B = {b}.\n"
)


# --------------------------------------------------------------------------- XDC
def _out_pair(name, p, n):
    return (
        f"set_property IOSTANDARD LVDS_25 [get_ports {{{name}_p {name}_n}}]\n"
        f"set_property PACKAGE_PIN {p} [get_ports {name}_p]\n"
        f"set_property PACKAGE_PIN {n} [get_ports {name}_n]\n"
        f"set_output_delay -clock $CLK -max  2.0 [get_ports {{{name}_p {name}_n}}]\n"
        f"set_output_delay -clock $CLK -min -2.0 [get_ports {{{name}_p {name}_n}}]\n"
    )


def _in_pair(name, p, n):
    return (
        f"set_property IOSTANDARD LVDS_25 [get_ports {{{name}_p {name}_n}}]\n"
        f"set_property PACKAGE_PIN {p} [get_ports {name}_p]\n"
        f"set_property PACKAGE_PIN {n} [get_ports {name}_n]\n"
        f"set_property DIFF_TERM TRUE  [get_ports {name}_p]\n"
        f"set_input_delay -clock $CLK -max 3.0 [get_ports {{{name}_p {name}_n}}]\n"
        f"set_input_delay -clock $CLK -min 0.5 [get_ports {{{name}_p {name}_n}}]\n"
    )


def gen_xdc(variant, spec):
    p = PORTS
    out = [GEN_HEADER.format(variant=variant, a=spec["a"], b=spec["b"]),
           "\n",
           "# Pin constraints: the LVDS SPI lanes per cable, plus I2C on the freed\n"
           "# second-CIPO balls for any 'imu' port. Added explicitly by\n"
           "# scripts/build_fabric.tcl -- it must NOT live in the globbed constraints/\n"
           "# dir, or the plain acquisition build would double-assign these ports.\n"
           "# The second-CIPO balls are LVCMOS25 I2C on an imu port and LVDS_25 (CIPO1)\n"
           "# on an lvds/128-ch port -- same physical balls, reconfigured per bitstream.\n\n",
           f"set CLK [get_clocks {CLK}]\n\n"]
    for port in PORT_ORDER:
        d = p[port]
        idx = d["idx"]
        base = f"spi_lvds_{idx}"
        mode = spec[port]
        out.append("#" + "=" * 78 + "\n")
        out.append(f"# PORT {port.upper()} (spi_lvds_{idx}) -- "
                   + ("64-ch, CIPO0 only + I2C on the freed CIPO1 balls\n" if mode == "imu"
                      else "128-ch, full CIPO0 + CIPO1 LVDS\n"))
        out.append("#" + "=" * 78 + "\n")
        out.append("# SCLK / CSN / COPI (broadcast outputs)\n")
        out.append(_out_pair(f"{base}_sclk", *d["sclk"]))
        out.append(_out_pair(f"{base}_csn", *d["csn"]))
        out.append(_out_pair(f"{base}_copi", *d["copi"]))
        out.append("# CIPO0 (input)\n")
        out.append(_in_pair(f"{base}_cipo0", *d["cipo0"]))
        if mode == "lvds":
            out.append("# CIPO1 (input)\n")
            out.append(_in_pair(f"{base}_cipo1", *d["cipo1"]))
        out.append("# Slew / drive on this port's outputs\n")
        out.append(f"set_property SLEW FAST [get_ports {{{base}_sclk_p {base}_csn_p {base}_copi_p}}]\n")
        out.append(f"set_property DRIVE 12  [get_ports {{{base}_sclk_p {base}_csn_p {base}_copi_p}}]\n\n")
        if mode == "imu":
            scl, sda = d["cipo1"]  # scl = cipo1_p ball, sda = cipo1_n ball
            pfx = d["iic_pfx"]
            out.append(f"# I2C on the freed CIPO1 balls (scl {scl}, sda {sda}); open-drain LVCMOS25.\n")
            out.append(f"set_property PACKAGE_PIN {scl} [get_ports {pfx}_scl_io]\n")
            out.append(f"set_property PACKAGE_PIN {sda} [get_ports {pfx}_sda_io]\n")
            out.append(f"set_property IOSTANDARD LVCMOS25 [get_ports {{{pfx}_scl_io {pfx}_sda_io}}]\n")
            out.append(f"set_property SLEW SLOW           [get_ports {{{pfx}_scl_io {pfx}_sda_io}}]\n")
            out.append(f"set_property DRIVE 8             [get_ports {{{pfx}_scl_io {pfx}_sda_io}}]\n\n")
    return "".join(out)


# ----------------------------------------------------------------------- overlay
def gen_overlay(variant, spec):
    imu_ports = [pt for pt in PORT_ORDER if spec[pt] == "imu"]
    out = [GEN_HEADER.format(variant=variant, a=spec["a"], b=spec["b"]),
           "\n",
           "# BD overlay: sourced AFTER design_1_bd.tcl, it transforms the stock\n"
           "# acquisition design_1 in place. For each 'imu' cable it swaps the LVDS\n"
           "# buffer for the CIPO0-only fork (freeing the CIPO1 balls) and grafts an\n"
           "# AXI IIC onto GP0; 'lvds' cables are left as the stock 128-ch buffer.\n\n",
           "current_bd_design design_1\n\n"]

    # 1. Swap the LVDS buffer for each imu port; leave lvds ports untouched.
    for pt in imu_ports:
        d = PORTS[pt]
        idx = d["idx"]
        out.append(f"# --- Port {pt.upper()}: CIPO0-only buffer, LVDS side re-exposed as plain ports ---\n")
        out.append(f"delete_bd_objs [get_bd_cells intan_spi_lvds_buffer_{idx}] "
                   f"[get_bd_intf_ports spi_lvds_{idx}]\n")
        out.append(f"create_bd_cell -type module -reference intan_spi_lvds_buffer_cipo0 "
                   f"intan_spi_lvds_buffer_{idx}\n")
        out.append(f"connect_bd_intf_net [get_bd_intf_pins data_generator/{d['dg']}] "
                   f"[get_bd_intf_pins intan_spi_lvds_buffer_{idx}/intan_spi]\n")
        out.append(f"foreach {{suf dir}} {{sclk_p O sclk_n O csn_p O csn_n O copi_p O copi_n O "
                   f"cipo0_p I cipo0_n I}} {{\n")
        out.append(f"    create_bd_port -dir $dir spi_lvds_{idx}_$suf\n")
        out.append(f"    connect_bd_net [get_bd_ports spi_lvds_{idx}_$suf] "
                   f"[get_bd_pins intan_spi_lvds_buffer_{idx}/spi_$suf]\n")
        out.append("}\n\n")

    # 2. Graft one AXI IIC per imu port onto the GP0 smartconnect.
    if imu_ports:
        num_mi = 3 + len(imu_ports)  # stock is 3 (regs, cdma, stim)
        out.append(f"# Grow the GP0 smartconnect (stock 3 masters) for the {len(imu_ports)} IIC(s).\n")
        out.append(f"set_property -dict [list CONFIG.NUM_MI {{{num_mi}}}] [get_bd_cells smartconnect_0]\n\n")
        for i, pt in enumerate(imu_ports):
            d = PORTS[pt]
            mi = 3 + i
            out.append(f"# --- Port {pt.upper()}: {d['iic']} at {d['base']} on smartconnect M0{mi} ---\n")
            out.append(f"create_bd_cell -type ip -vlnv xilinx.com:ip:axi_iic:2.1 {d['iic']}\n")
            out.append(f"set_property -dict [list CONFIG.C_SCL_INERTIAL_DELAY {{5}} "
                       f"CONFIG.IIC_FREQ_KHZ {{100}}] [get_bd_cells {d['iic']}]\n")
            out.append(f"connect_bd_intf_net [get_bd_intf_pins smartconnect_0/M0{mi}_AXI] "
                       f"[get_bd_intf_pins {d['iic']}/S_AXI]\n")
            out.append(f"make_bd_intf_pins_external [get_bd_intf_pins {d['iic']}/IIC]\n")
            out.append(f"set_property name {d['iic_pfx']} [get_bd_intf_ports IIC_0]\n")
            out.append(f"connect_bd_net -net clk_wiz_0_84M_clk_out2 "
                       f"[get_bd_pins {d['iic']}/s_axi_aclk]\n")
            out.append(f"connect_bd_net -net proc_sys_reset_175MHz_interconnect_aresetn "
                       f"[get_bd_pins {d['iic']}/s_axi_aresetn]\n")
            out.append(f"assign_bd_address -offset {d['base']} -range 0x00010000 "
                       f"-target_address_space [get_bd_addr_spaces processing_system7_0/Data] "
                       f"[get_bd_addr_segs {d['iic']}/S_AXI/Reg] -force\n\n")

    out.append("validate_bd_design\n")
    out.append("save_bd_design\n")
    return "".join(out)


# -------------------------------------------------------------------------- main
def emit(variant, spec):
    overlay_path = os.path.join(OVERLAY_DIR, f"{variant}_overlay.tcl")
    xdc_path = os.path.join(XDC_DIR, f"{variant}_pins.xdc")
    os.makedirs(XDC_DIR, exist_ok=True)
    with open(overlay_path, "w") as f:
        f.write(gen_overlay(variant, spec))
    with open(xdc_path, "w") as f:
        f.write(gen_xdc(variant, spec))
    print(f"[build_fabric] wrote {os.path.relpath(overlay_path, ROOT)}")
    print(f"[build_fabric] wrote {os.path.relpath(xdc_path, ROOT)}")
    return overlay_path, xdc_path


def main():
    args = [a for a in sys.argv[1:]]
    emit_only = "--emit-only" in args
    args = [a for a in args if not a.startswith("--")]
    if len(args) != 1 or args[0] not in VARIANTS:
        sys.exit(f"usage: build_fabric.py <{'|'.join(VARIANTS)}> [--emit-only]")
    variant = args[0]
    spec = VARIANTS[variant]
    emit(variant, spec)
    if emit_only:
        return
    xilinx = os.environ.get("XILINX_ROOT", "/opt/Xilinx/2025.1")
    vivado = os.path.join(xilinx, "Vivado", "bin", "vivado")
    cmd = [vivado, "-mode", "batch", "-nojournal",
           "-log", f"vivado_{variant}_build.log",
           "-source", os.path.join(ROOT, "scripts", "build_fabric.tcl"),
           "-tclargs", variant]
    print(f"[build_fabric] {' '.join(cmd)}")
    rc = subprocess.call(cmd, cwd=ROOT)
    # Vivado's launcher can exit 0 even when its Tcl init fails (e.g. a missing
    # host lib), so verify the .xsa was actually produced rather than trusting rc.
    xsa = os.path.join(ROOT, f"vivado_{variant}", f"{variant}.xsa")
    if rc != 0 or not os.path.exists(xsa):
        sys.exit(f"[build_fabric] FAILED for {variant}: vivado rc={rc}, "
                 f"xsa_exists={os.path.exists(xsa)} (see vivado_{variant}_build.log)")
    print(f"[build_fabric] OK: {os.path.relpath(xsa, ROOT)}")


if __name__ == "__main__":
    main()
